/**
 * BarangayAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2019-07-14T05:55:41Z
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.7
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.BarangayApi) {
      root.BarangayApi = {};
    }
    root.BarangayApi.BarangayComplaintModel = factory(root.BarangayApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The BarangayComplaintModel model module.
   * @module model/BarangayComplaintModel
   * @version 2019-07-14T05:55:41Z
   */

  /**
   * Constructs a new <code>BarangayComplaintModel</code>.
   * @alias module:model/BarangayComplaintModel
   * @class
   */
  var exports = function() {
    var _this = this;










  };

  /**
   * Constructs a <code>BarangayComplaintModel</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/BarangayComplaintModel} obj Optional instance to populate.
   * @return {module:model/BarangayComplaintModel} The populated <code>BarangayComplaintModel</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('complaint_id')) {
        obj['complaint_id'] = ApiClient.convertToType(data['complaint_id'], 'String');
      }
      if (data.hasOwnProperty('attachment_id')) {
        obj['attachment_id'] = ApiClient.convertToType(data['attachment_id'], 'String');
      }
      if (data.hasOwnProperty('complaint_desc')) {
        obj['complaint_desc'] = ApiClient.convertToType(data['complaint_desc'], 'String');
      }
      if (data.hasOwnProperty('latitude')) {
        obj['latitude'] = ApiClient.convertToType(data['latitude'], 'String');
      }
      if (data.hasOwnProperty('longitude')) {
        obj['longitude'] = ApiClient.convertToType(data['longitude'], 'String');
      }
      if (data.hasOwnProperty('type')) {
        obj['type'] = ApiClient.convertToType(data['type'], 'String');
      }
      if (data.hasOwnProperty('user_id')) {
        obj['user_id'] = ApiClient.convertToType(data['user_id'], 'String');
      }
      if (data.hasOwnProperty('status')) {
        obj['status'] = ApiClient.convertToType(data['status'], 'String');
      }
      if (data.hasOwnProperty('create_date')) {
        obj['create_date'] = ApiClient.convertToType(data['create_date'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} complaint_id
   */
  exports.prototype['complaint_id'] = undefined;
  /**
   * @member {String} attachment_id
   */
  exports.prototype['attachment_id'] = undefined;
  /**
   * @member {String} complaint_desc
   */
  exports.prototype['complaint_desc'] = undefined;
  /**
   * @member {String} latitude
   */
  exports.prototype['latitude'] = undefined;
  /**
   * @member {String} longitude
   */
  exports.prototype['longitude'] = undefined;
  /**
   * @member {String} type
   */
  exports.prototype['type'] = undefined;
  /**
   * @member {String} user_id
   */
  exports.prototype['user_id'] = undefined;
  /**
   * @member {String} status
   */
  exports.prototype['status'] = undefined;
  /**
   * @member {String} create_date
   */
  exports.prototype['create_date'] = undefined;



  return exports;
}));


