/**
 * BarangayAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2019-07-14T05:55:41Z
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.7
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD. Register as an anonymous module.
    define(['ApiClient'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    module.exports = factory(require('../ApiClient'));
  } else {
    // Browser globals (root is window)
    if (!root.BarangayApi) {
      root.BarangayApi = {};
    }
    root.BarangayApi.BarangayDocumentModel = factory(root.BarangayApi.ApiClient);
  }
}(this, function(ApiClient) {
  'use strict';




  /**
   * The BarangayDocumentModel model module.
   * @module model/BarangayDocumentModel
   * @version 2019-07-14T05:55:41Z
   */

  /**
   * Constructs a new <code>BarangayDocumentModel</code>.
   * @alias module:model/BarangayDocumentModel
   * @class
   */
  var exports = function() {
    var _this = this;








  };

  /**
   * Constructs a <code>BarangayDocumentModel</code> from a plain JavaScript object, optionally creating a new instance.
   * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
   * @param {Object} data The plain JavaScript object bearing properties of interest.
   * @param {module:model/BarangayDocumentModel} obj Optional instance to populate.
   * @return {module:model/BarangayDocumentModel} The populated <code>BarangayDocumentModel</code> instance.
   */
  exports.constructFromObject = function(data, obj) {
    if (data) {
      obj = obj || new exports();

      if (data.hasOwnProperty('document_id')) {
        obj['document_id'] = ApiClient.convertToType(data['document_id'], 'String');
      }
      if (data.hasOwnProperty('approve_date')) {
        obj['approve_date'] = ApiClient.convertToType(data['approve_date'], 'String');
      }
      if (data.hasOwnProperty('attachment_id')) {
        obj['attachment_id'] = ApiClient.convertToType(data['attachment_id'], 'String');
      }
      if (data.hasOwnProperty('create_date')) {
        obj['create_date'] = ApiClient.convertToType(data['create_date'], 'String');
      }
      if (data.hasOwnProperty('status')) {
        obj['status'] = ApiClient.convertToType(data['status'], 'String');
      }
      if (data.hasOwnProperty('reason')) {
        obj['reason'] = ApiClient.convertToType(data['reason'], 'String');
      }
      if (data.hasOwnProperty('user_id')) {
        obj['user_id'] = ApiClient.convertToType(data['user_id'], 'String');
      }
    }
    return obj;
  }

  /**
   * @member {String} document_id
   */
  exports.prototype['document_id'] = undefined;
  /**
   * @member {String} approve_date
   */
  exports.prototype['approve_date'] = undefined;
  /**
   * @member {String} attachment_id
   */
  exports.prototype['attachment_id'] = undefined;
  /**
   * @member {String} create_date
   */
  exports.prototype['create_date'] = undefined;
  /**
   * @member {String} status
   */
  exports.prototype['status'] = undefined;
  /**
   * @member {String} reason
   */
  exports.prototype['reason'] = undefined;
  /**
   * @member {String} user_id
   */
  exports.prototype['user_id'] = undefined;



  return exports;
}));


