/**
 * BarangayAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2019-07-14T05:55:41Z
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.7
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BarangayApi);
  }
}(this, function(expect, BarangayApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new BarangayApi.BarangayDocumentModel();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('BarangayDocumentModel', function() {
    it('should create an instance of BarangayDocumentModel', function() {
      // uncomment below and update the code to test BarangayDocumentModel
      //var instance = new BarangayApi.BarangayDocumentModel();
      //expect(instance).to.be.a(BarangayApi.BarangayDocumentModel);
    });

    it('should have the property documentId (base name: "document_id")', function() {
      // uncomment below and update the code to test the property documentId
      //var instance = new BarangayApi.BarangayDocumentModel();
      //expect(instance).to.be();
    });

    it('should have the property approveDate (base name: "approve_date")', function() {
      // uncomment below and update the code to test the property approveDate
      //var instance = new BarangayApi.BarangayDocumentModel();
      //expect(instance).to.be();
    });

    it('should have the property attachmentId (base name: "attachment_id")', function() {
      // uncomment below and update the code to test the property attachmentId
      //var instance = new BarangayApi.BarangayDocumentModel();
      //expect(instance).to.be();
    });

    it('should have the property createDate (base name: "create_date")', function() {
      // uncomment below and update the code to test the property createDate
      //var instance = new BarangayApi.BarangayDocumentModel();
      //expect(instance).to.be();
    });

    it('should have the property status (base name: "status")', function() {
      // uncomment below and update the code to test the property status
      //var instance = new BarangayApi.BarangayDocumentModel();
      //expect(instance).to.be();
    });

    it('should have the property reason (base name: "reason")', function() {
      // uncomment below and update the code to test the property reason
      //var instance = new BarangayApi.BarangayDocumentModel();
      //expect(instance).to.be();
    });

    it('should have the property userId (base name: "user_id")', function() {
      // uncomment below and update the code to test the property userId
      //var instance = new BarangayApi.BarangayDocumentModel();
      //expect(instance).to.be();
    });

  });

}));
