/**
 * BarangayAPI
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2019-07-14T05:55:41Z
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 *
 * Swagger Codegen version: 2.4.7
 *
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', '../../src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require('../../src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.BarangayApi);
  }
}(this, function(expect, BarangayApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new BarangayApi.BarangayUserModel();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('BarangayUserModel', function() {
    it('should create an instance of BarangayUserModel', function() {
      // uncomment below and update the code to test BarangayUserModel
      //var instance = new BarangayApi.BarangayUserModel();
      //expect(instance).to.be.a(BarangayApi.BarangayUserModel);
    });

    it('should have the property userId (base name: "user_id")', function() {
      // uncomment below and update the code to test the property userId
      //var instance = new BarangayApi.BarangayUserModel();
      //expect(instance).to.be();
    });

    it('should have the property username (base name: "username")', function() {
      // uncomment below and update the code to test the property username
      //var instance = new BarangayApi.BarangayUserModel();
      //expect(instance).to.be();
    });

    it('should have the property password (base name: "password")', function() {
      // uncomment below and update the code to test the property password
      //var instance = new BarangayApi.BarangayUserModel();
      //expect(instance).to.be();
    });

    it('should have the property address (base name: "address")', function() {
      // uncomment below and update the code to test the property address
      //var instance = new BarangayApi.BarangayUserModel();
      //expect(instance).to.be();
    });

    it('should have the property birtdate (base name: "birtdate")', function() {
      // uncomment below and update the code to test the property birtdate
      //var instance = new BarangayApi.BarangayUserModel();
      //expect(instance).to.be();
    });

    it('should have the property createdate (base name: "createdate")', function() {
      // uncomment below and update the code to test the property createdate
      //var instance = new BarangayApi.BarangayUserModel();
      //expect(instance).to.be();
    });

    it('should have the property firstname (base name: "firstname")', function() {
      // uncomment below and update the code to test the property firstname
      //var instance = new BarangayApi.BarangayUserModel();
      //expect(instance).to.be();
    });

    it('should have the property lastname (base name: "lastname")', function() {
      // uncomment below and update the code to test the property lastname
      //var instance = new BarangayApi.BarangayUserModel();
      //expect(instance).to.be();
    });

    it('should have the property mobilenumber (base name: "mobilenumber")', function() {
      // uncomment below and update the code to test the property mobilenumber
      //var instance = new BarangayApi.BarangayUserModel();
      //expect(instance).to.be();
    });

    it('should have the property zipcode (base name: "zipcode")', function() {
      // uncomment below and update the code to test the property zipcode
      //var instance = new BarangayApi.BarangayUserModel();
      //expect(instance).to.be();
    });

    it('should have the property civilStatus (base name: "civil_status")', function() {
      // uncomment below and update the code to test the property civilStatus
      //var instance = new BarangayApi.BarangayUserModel();
      //expect(instance).to.be();
    });

    it('should have the property ctcNo (base name: "ctc_no")', function() {
      // uncomment below and update the code to test the property ctcNo
      //var instance = new BarangayApi.BarangayUserModel();
      //expect(instance).to.be();
    });

    it('should have the property tinNo (base name: "tin_no")', function() {
      // uncomment below and update the code to test the property tinNo
      //var instance = new BarangayApi.BarangayUserModel();
      //expect(instance).to.be();
    });

    it('should have the property placeOfBirth (base name: "place_of_birth")', function() {
      // uncomment below and update the code to test the property placeOfBirth
      //var instance = new BarangayApi.BarangayUserModel();
      //expect(instance).to.be();
    });

    it('should have the property weight (base name: "weight")', function() {
      // uncomment below and update the code to test the property weight
      //var instance = new BarangayApi.BarangayUserModel();
      //expect(instance).to.be();
    });

    it('should have the property height (base name: "height")', function() {
      // uncomment below and update the code to test the property height
      //var instance = new BarangayApi.BarangayUserModel();
      //expect(instance).to.be();
    });

    it('should have the property controlNo (base name: "control_no")', function() {
      // uncomment below and update the code to test the property controlNo
      //var instance = new BarangayApi.BarangayUserModel();
      //expect(instance).to.be();
    });

    it('should have the property contactNo (base name: "contact_no")', function() {
      // uncomment below and update the code to test the property contactNo
      //var instance = new BarangayApi.BarangayUserModel();
      //expect(instance).to.be();
    });

    it('should have the property profession (base name: "profession")', function() {
      // uncomment below and update the code to test the property profession
      //var instance = new BarangayApi.BarangayUserModel();
      //expect(instance).to.be();
    });

    it('should have the property grossIncome (base name: "gross_income")', function() {
      // uncomment below and update the code to test the property grossIncome
      //var instance = new BarangayApi.BarangayUserModel();
      //expect(instance).to.be();
    });

    it('should have the property attachmentId (base name: "attachment_id")', function() {
      // uncomment below and update the code to test the property attachmentId
      //var instance = new BarangayApi.BarangayUserModel();
      //expect(instance).to.be();
    });

    it('should have the property gender (base name: "gender")', function() {
      // uncomment below and update the code to test the property gender
      //var instance = new BarangayApi.BarangayUserModel();
      //expect(instance).to.be();
    });

  });

}));
